services:
  gic-front-prod:
    build:
      context: .
      target: prod
    container_name: gic-front-prod
    ports:
      - "3000:80"
    restart: always

  gic-front-dev:
    build:
      context: .
      target: dev
    container_name: gic-front-dev
    ports:
      - "4200:80"
    restart: always