export enum Permission {
    // HISTORY
    HISTORY_AGENCY_VIEW = "AGENCY_HISTORY",
    HISTORY_AGENTS_VIEW = "AGENT_HISTORY",
    HISTORY_CASHIER_VIEW = "CASHIER_HISTORY",
    HISTORY_CASHIER_DETAIL = "CASHIER_HISTORY_DETAIL",

    // REPORTS
    REPORT_VIEW = "REPORT",

    // BALANCE
    BALANCE_OPERATION_VIEW = "BALANCE_VIEW",
    BALANCE_COMMISSION_VIEW = "COMMISSION_VIEW",

    // AGENCY MANAGEMENT
    AGENCY_VIEW = "AGENCY_LIST",
    AGENCY_OPEN = "AGENCY_OPEN",
    AGENCY_DETAIL = "AGENCY_DETAIL",
    AGENCY_ENABLE = "AGENCY_ENABLED",

    // CASHIER MANAGEMENT
    CASHIER_ALL_VIEW = "CASHIER_LIST_AGENT",
    CASHIER_VIEW = "CASHIER_LIST_AGENCY",
    CASHIER_ENABLE = "CASHIER_ENABLED",

    // ROLE MANAGEMENT
    ROLE_DETAIL = "ROLE_DETAIL",
    ROLE_VIEW = "ROLE_LIST",

    // FUNDS TRANSFER
    FUNDS_TRANSFER_VIEW = "FUNDS_TRANSFER"
}

export const GROUP_PERMISSIONS = {
    HISTORY: [
        Permission.HISTORY_AGENCY_VIEW,
        Permission.HISTORY_AGENTS_VIEW,
        Permission.HISTORY_CASHIER_VIEW,
        Permission.HISTORY_CASHIER_DETAIL,
    ],

    REPORT: [Permission.REPORT_VIEW],

    BALANCE: [
        Permission.BALANCE_OPERATION_VIEW,
        Permission.BALANCE_COMMISSION_VIEW,
    ],

    MANAGEMENT: [
        // AGENCY MANAGEMENT
        Permission.AGENCY_VIEW,
        Permission.AGENCY_OPEN,
        Permission.AGENCY_DETAIL,
        Permission.AGENCY_ENABLE,

        // CASHIER MANAGEMENT
        Permission.CASHIER_ALL_VIEW,
        Permission.CASHIER_VIEW,
        Permission.CASHIER_ENABLE,

        // ROLE MANAGEMENT
        Permission.ROLE_DETAIL,
        Permission.ROLE_VIEW,

        // FUNDS TRANSFER
        Permission.FUNDS_TRANSFER_VIEW,
    ]
} as const;
